export const FETCH_FILMS_PENDING = 'FETCH_FILMS_PENDING';
export const FETCH_FILMS_FULFILLED = 'FETCH_FILMS_FULFILLED';
export const FETCH_FILMS_REJECTED = 'FETCH_FILMS_REJECTED';
export const SEARCH_FILMS = 'SEARCH_FILMS';