export const FETCH_PEOPLE_PENDING = 'FETCH_PEOPLE_PENDING';
export const FETCH_PEOPLE_FULFILLED = 'FETCH_PEOPLE_FULFILLED';
export const FETCH_PEOPLE_REJECTED = 'FETCH_PEOPLE_REJECTED';
export const SEARCH_PEOPLE = 'SEARCH_PEOPLE';