export const FETCH_SPACESHIPS_PENDING = 'FETCH_SPACESHIPS_PENDING';
export const FETCH_SPACESHIPS_FULFILLED = 'FETCH_SPACESHIPS_FULFILLED';
export const FETCH_SPACESHIPS_REJECTED = 'FETCH_SPACESHIPS_REJECTED';
export const SEARCH_SPACESHIPS = 'SEARCH_SPACESHIPS';